### ISSUE TITLE
Synvert fails to honor .ruby-version file

### ISSUE THREAD

**Issue by brandondrew** [synvert-hq/synvert#3]
Synvert seems to assume I am using system Ruby, but I never ever use System Ruby and no one I know uses it.  Even though Synvert has the path to my project, it doesn't use the .ruby-version file there.

**Comment by flyerhzm** [comment]
@brandondrew it runs the following command
```
/bin/bash -c -l 'ruby -v'
```
or
```
/bin/zsh -c -l 'ruby -v'
```

If you use the rvm, it supposed to use the rvm default ruby instead of system ruby.

It won't check the .ruby-version file, synvert-ruby can be installed once and check all your projects no matter what ruby version your projects are using.

I will add configuration to allow you set the path of synvert-ruby cli, so that you can install the synvert gem by yourself.

**Comment by flyerhzm** [comment]
@brandondrew I found one issue during app started, it supposed to ask you install synvert gem if the gem is not installed, please install the latest synvert app and try again https://github.com/synvert-hq/synvert-gui/releases/tag/v1.12.0

If it still doesn't install the synvert gem properly, you can set the bin path of the synvert gem.

**Comment by brandondrew** [comment]
I get `zsh:1: permission denied: /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin`

The permissions are as follows:

```
brandon@Air ~ % ls -hal /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin                          
total 8
drwxr-xr-x   3 brandon  staff    96B Apr 14 15:20 .
drwxr-xr-x  17 brandon  staff   544B Apr 14 15:20 ..
-rwxr-xr-x   1 brandon  staff   173B Apr 14 15:20 synvert-ruby
```

**Comment by flyerhzm** [comment]
@brandondrew did you manually set the bin path? could you set it to `/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin/synvert-ruby` instead?

**Comment by flyerhzm** [comment]
@brandondrew the name `bin path` may be confusing, I renamed it to `command path` in version 1.12.1
https://github.com/synvert-hq/synvert-gui/releases/tag/v1.12.1

**Comment by brandondrew** [comment]
I changed my bin path to the path you gave, but I still get this error message when I start up

```
Synvert gem not found. Run `gem install synvert`.
```

**Comment by flyerhzm** [comment]
@brandondrew please make some tests in your shell

```
$ /zsh/bin -c -l '/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin/synvert-ruby -v'
```

and

```
$ /zsh/bin -c -l 'synvert-ruby -v'
```

It supposed to get synvert-ruby version, like `1.10.3 (with synvert-core 1.35.1)`

**Comment by brandondrew** [comment]
I assume you meant `/bin/zsh`?

```shell
brandon@Air ~ % /bin/zsh -c -l '/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin/synvert-ruby -v'     
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- synvert/core (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/lib/synvert.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/synvert-1.10.2/bin/synvert-ruby:5:in `<main>'
brandon@Air ~ % 
```

and 

```
brandon@Air ~ % /bin/zsh -c -l 'synvert-ruby -v'    
1.10.2 (with synvert-core 1.35.0
```

**Comment by flyerhzm** [comment]
@brandondrew looks like it works with the `synvert-ruby` instead of the absolute path, could you unset the binPath or commandPath then restart the app?

**Comment by brandondrew** [comment]
Okay, I still get this

```
Failed to install the synvert gem. ERROR: While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```

when I click "Install Now" to install the gem.

**Comment by flyerhzm** [comment]
@brandondrew sorry for the trouble, I'll spend some time to install rbenv locally and fix the issue.

**Comment by brandondrew** [comment]
Thanks!

**Comment by flyerhzm** [comment]
@brandondrew I've switched to rbenv, looks if you set command path to `/Users/brandon/.rbenv/shims/synvert-ruby`, it should work for you.

**Comment by brandondrew** [comment]
I just set the command path to that value and I still got this error:

```
Failed to install the synvert gem. ERROR: While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```

I notice that my version is behind yours:
```
$ /bin/zsh -c -l "$HOME/.rbenv/shims/synvert-ruby -v"
1.10.2 (with synvert-core 1.35.0
```

So I upgraded it from the command line.  I then restarted Synvert, and was prompted to install them from the GUI app, and accepted, and got this error again:

```
Failed to install the synvert gem. ERROR: While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```

**Comment by flyerhzm** [comment]
@brandondrew turn out it needs to use `/Users/brandon/.rbenv/shims/gem` to install the synvert gem.

Please install the Synvert version 1.13.0 https://github.com/synvert-hq/synvert-gui/releases/tag/v1.13.0, and set `bin_path` (yes, I reverted command_path to bin_path) to `/Users/brandon/.rbenv/shims`, I'm pretty sure it's working for rbenv now.
