### ISSUE TITLE
Synvert appears unresponsive because responses vanish instantly.

### ISSUE THREAD

**Issue by brandondrew** [synvert-hq/synvert#5]
When I choose a snippet and press the "Search" button, it appears like Synvert does absolutely nothing.  But after a while I figured out that it is (for less than a second!) putting a (small!) message in the center of the Synvert window (which is a color of gray only slightly lighter than the window's background).  This is almost impossible to read.  The message should remain visible until either the user does something else, or at least a few seconds have elapsed.  And it would be helpful for the contrast to be increased, and perhaps maybe the font size.

**Comment by flyerhzm** [comment]
@brandondrew I have made the notification message more obvious, and make it open until you dismiss it explicitly.
It will be available in the next version.

**Comment by brandondrew** [comment]
Thanks!  Although I think it's best if it doesn't block the user from doing other things.  Can it be implicitly dismissed when the user clicks elsewhere in the UI?
